# Generated by Django 4.2.4 on 2023-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travello", "0002_destination_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
