# Generated by Django 4.2.4 on 2023-10-06 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
                ("review_comment", models.TextField(max_length=200)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.DeleteModel(
            name="CustomerFeedback",
        ),
    ]
